neighborhoods = [
    "Allston",
    "Back Bay",
    "Bay Village",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dorchester",
    "Downtown",
    "East Boston",
    "Fenway-Kenmore",
    "Hyde Park",
    "Jamaica Plain",
    "Mattapan",
    "Mission Hill",
    "North End",
    "Roslindale",
    "Roxbury",
    "South Boston",
    "South End",
    "West End",
    "West Roxbury",
    "Wharf District",
]

services = [
    "Beauty Services",
    "Tailoring / Garments",
    "Photography",
    "Art / Crafts",
    "Home Repair",
    "Consulting Services",
    "Accounting",
    "Food",
    "Interior Design",
    "Tutoring",
    "Graphic Design",
    "Pet Sitting",
    "Freelance Writing",
    "Fitness / Sports / Coaching"
]
